### PR TITLE
KEYCLOAK-2474 Added docs for custom REST endpoints, SPI and JPA entities

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by ewjmulder** [comment]
Looks good Marek, thanks for taking care of this as well! I think this should provide the expert Keycloak user with enough information to get going. Anyone who wants to do these kind of advanced extensions must be an expert Keycloak user / developer anyway.

P.S. The English grammer is not always perfect, but I guess that is not very important as long as the message is clear, which it is.

**Comment by mposolda** [comment]
My english sucks, I know :/ If you have opportunity, you can cherry-pick my commit and fix the grammar and then send another PR with both commits and close this one. Or you can send PR just after this PR is merged (but not sure if we catch it till 2.0.0.CR1 release as it's planned this week. However fixing docs grammar after release should be fine too)

**Comment by ewjmulder** [comment]
As an alternative to your suggested solutions, I made a fork of your fork and created a PR on that, so you can merge them together if you agree with the changes, see: https://github.com/mposolda/server_development_guide/pull/1

**Comment by mposolda** [comment]
Thanks! PR now contains the corrections from Eric.

**Comment by ewjmulder** [comment]
That was a quick followup, nice.
As long as we're talking about language/spelling here, it's Eri**k** actually... :)

**Comment by mposolda** [comment]
ouch, Sorry Erik for garble your name. Will try to avoid it next time :)

**Pull request merged**
